// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWV7bX-cOObJ9eBw-TRGOueTSoPIURe4M',
    appId: '1:1011908637451:android:9b175c5315562259eba80e',
    messagingSenderId: '1011908637451',
    projectId: 'fire-fighting-system-41880',
    databaseURL: 'https://fire-fighting-system-41880-default-rtdb.firebaseio.com',
    storageBucket: 'fire-fighting-system-41880.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAROYTlJqNYzOZ_iCGu05Uo0LRRCSaytBg',
    appId: '1:1011908637451:ios:efbc498f48005101eba80e',
    messagingSenderId: '1011908637451',
    projectId: 'fire-fighting-system-41880',
    databaseURL: 'https://fire-fighting-system-41880-default-rtdb.firebaseio.com',
    storageBucket: 'fire-fighting-system-41880.appspot.com',
    iosBundleId: 'com.example.firefightingsystem',
  );
}
